# Usa una imagen base oficial de Node
FROM node:22-alpine

# Directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Instala Angular CLI globalmente
RUN npm install -g @angular/cli

# Copia archivos de dependencias primero para aprovechar el caching de Docker
COPY package*.json ./

# Instala las dependencias (con legacy-peer-deps si es necesario)
RUN npm install --legacy-peer-deps

# Copia el resto del código
COPY . .

# Expone el puerto que usa Angular en desarrollo
EXPOSE 4200

# Comando por defecto (sin HMR pero con polling para detectar cambios)
# CMD ["ng", "serve" ,"--no-hmr", "--host", "0.0.0.0", "--disable-host-check", "--poll=100"]
CMD ["ng", "serve", "--no-hmr", "--host", "0.0.0.0", "--disable-host-check", "--poll=100", "--port=4201"]