 services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: flooring1-dev
    ports:
      - "4201:4201"   # Mapea puerto local al del contenedor
    volumes:
      - .:/usr/src/app               # Monta el código fuente en el contenedor
      - /usr/src/app/node_modules    # Evita sobrescribir node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true    # Mejora el watch de archivos en Docker