name: Deploy to Firebase

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Create environment file
        run: node build-env.js
        env:
          FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
          FACEBOOK_TOKEN: ${{ secrets.FACEBOOK_TOKEN }}
          CONTACT_PHONE: ${{ secrets.CONTACT_PHONE }}
          CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}
          CONTACT_ADDRESS: ${{ secrets.CONTACT_ADDRESS }}

      - name: Build Angular app
        run: npm run build -- --configuration=production

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: discountflooring-1e2c6
          channelId: live